# Generated by Django 4.1 on 2023-04-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_blog_contact_galary_homeblog_homeevent_latestcause'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
