# Generated by Django 4.1 on 2023-04-13 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
