# Generated by Django 4.1 on 2023-04-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_alter_galary_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galary',
        ),
    ]
