# Generated by Django 4.1 on 2023-04-13 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0007_delete_galary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galary-img')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
