# Generated by Django 4.1 on 2023-04-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0008_galary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galary',
        ),
    ]
