# Generated by Django 4.1 on 2023-04-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0010_galary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galary',
            name='image',
            field=models.ImageField(default='', upload_to='galary-img'),
        ),
    ]
