# Generated by Django 4.1 on 2023-04-25 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0012_remove_galary_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galary',
        ),
    ]
