# Generated by Django 4.1 on 2023-06-07 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0016_rename_blog_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
