# Generated by Django 4.1 on 2023-07-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0018_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
