# Generated by Django 4.1 on 2023-08-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0019_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
