# Generated by Django 5.0.6 on 2024-05-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0021_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtube',
            options={},
        ),
    ]
