# Generated by Django 5.0.6 on 2024-05-14 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0022_alter_youtube_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
