# Generated by Django 5.0.6 on 2024-05-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0024_mycategory_mygallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycategory',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
