# Generated by Django 5.0.6 on 2024-11-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0025_alter_mycategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content1',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content10',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content11',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content12',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content13',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content14',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content15',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content16',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content17',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content18',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content19',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content20',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content7',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content8',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='content9',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='himfoundation'),
        ),
    ]
